spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer.group-id: price
    consumer.auto.offset-reset: earliest
    consumer.key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    consumer.value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
    producer.value-serializer: org.apache.kafka.common.serialization.StringSerializer
    producer.batch-size: 800000
    producer.linger-ms: 100